name: Documenter
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/**'
      - 'test/**'
      - 'img/**'
      - 'validation/**'
      - 'change.log'
      - '.gitignore'
      - 'Project.toml'
  release:
    types: [published]
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - name: Update
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get install pandoc texlive-latex-recommended texlive-xetex texlive-luatex texlive-latex-extra texlive-lang-cyrillic texlive-doc-ru
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - name: Build and deploy
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
